rickshaw:
  css: [css/rickshaw.min.css, css/jquery-ui.css]
  jshead: [js/d3.v2.min.js, js/rickshaw.min.js, js/jquery.min.js, js/jquery-ui.min.js]
  cdn:
    css: 
      - "//cdn.strategiqcommerce.com/ajax/libs/rickshaw/1.2.1/rickshaw.min.css"
      - "//ajax.googleapis.com/ajax/libs/jqueryui/1.8/themes/base/jquery-ui.css"
    jshead:
      - "//d3js.org/d3.v2.min.js"
      - "//cdn.strategiqcommerce.com/ajax/libs/rickshaw/1.2.1/rickshaw.min.js"
      - "//ajax.googleapis.com/ajax/libs/jquery/1.6.2/jquery.min.js"
      - "//ajax.googleapis.com/ajax/libs/jqueryui/1.8.15/jquery-ui.min.js"
